//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Path : global::System.Configuration.ApplicationSettingsBase {
        
        private static Path defaultInstance = ((Path)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Path())));
        
        public static Path Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\trades.dat")]
        public string pathBinary {
            get {
                return ((string)(this["pathBinary"]));
            }
            set {
                this["pathBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\trades.csv")]
        public string pathCsv {
            get {
                return ((string)(this["pathCsv"]));
            }
            set {
                this["pathCsv"] = value;
            }
        }
    }
}
